
package Telas;

import Controles.TelaMenuControle;

public class TelaMenu extends javax.swing.JFrame {

    private final TelaMenuControle controles;

    /**
     * Creates new form TelaMenu
     */
    public TelaMenu() {
        initComponents();
        this.controles =  new TelaMenuControle(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fundoMenu = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        MenuCadastro = new javax.swing.JMenu();
        MenuItemCliente = new javax.swing.JMenuItem();
        MenuItemServicos = new javax.swing.JMenuItem();
        MenuItemUsuario = new javax.swing.JMenuItem();
        MenuOperacao = new javax.swing.JMenu();
        MenuItemAgenda = new javax.swing.JMenuItem();
        MenuRelatorio = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fundoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Imagens/Telas/fundoGeral.jpg"))); // NOI18N
        getContentPane().add(fundoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 670));

        jMenuBar2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        MenuCadastro.setText("Cadastro");
        MenuCadastro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        MenuItemCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MenuItemCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Imagens/Icones/cliente.png"))); // NOI18N
        MenuItemCliente.setText("Cliente");
        MenuCadastro.add(MenuItemCliente);

        MenuItemServicos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MenuItemServicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Imagens/Icones/pedidos.png"))); // NOI18N
        MenuItemServicos.setText("Serviços");
        MenuItemServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemServicosActionPerformed(evt);
            }
        });
        MenuCadastro.add(MenuItemServicos);

        MenuItemUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MenuItemUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Imagens/Icones/usuario.png"))); // NOI18N
        MenuItemUsuario.setText("Usuário");
        MenuCadastro.add(MenuItemUsuario);

        jMenuBar2.add(MenuCadastro);

        MenuOperacao.setText("Operacao");
        MenuOperacao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        MenuItemAgenda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MenuItemAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Imagens/Icones/brigadeiro.png"))); // NOI18N
        MenuItemAgenda.setText("Agenda");
        MenuItemAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAgendaActionPerformed(evt);
            }
        });
        MenuOperacao.add(MenuItemAgenda);

        jMenuBar2.add(MenuOperacao);

        MenuRelatorio.setText("Relatório");
        MenuRelatorio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuBar2.add(MenuRelatorio);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItemServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemServicosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuItemServicosActionPerformed

    private void MenuItemAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAgendaActionPerformed
        this.controles.NavegarParaAgenda();
    }//GEN-LAST:event_MenuItemAgendaActionPerformed

   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuCadastro;
    private javax.swing.JMenuItem MenuItemAgenda;
    private javax.swing.JMenuItem MenuItemCliente;
    private javax.swing.JMenuItem MenuItemServicos;
    private javax.swing.JMenuItem MenuItemUsuario;
    private javax.swing.JMenu MenuOperacao;
    private javax.swing.JMenu MenuRelatorio;
    private javax.swing.JLabel fundoMenu;
    private javax.swing.JMenuBar jMenuBar2;
    // End of variables declaration//GEN-END:variables
}
